# Generated by Django 4.0.5 on 2022-06-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_sal', models.IntegerField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
            ],
        ),
    ]
