# Generated by Django 4.0.5 on 2022-06-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCrud', '0002_remove_employee_emp_sal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='bisen', max_length=100),
            preserve_default=False,
        ),
    ]
