# Generated by Django 4.0.5 on 2022-06-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCrud', '0003_rename_fullname_employee_firstname_employee_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='Authorname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='Bookname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='Content_type',
        ),
    ]
